[package]
name = "kuriboh"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Memory",
]


